### ISSUE TITLE
POST vs PUT

### ISSUE THREAD

**Issue by wasadigi** [xajkep/Teaching-HEIGVD-TWEB-2015-Project#1]
Bonjour,

Faites attention: les bonnes pratiques REST demandent à ce que l'ajout de ressources se fasse avec la méthode POST (e.g. POST /students/) et que leur modification se fasse avec la méthode PUT (e.g. PUT /students/8839).

**Comment by julienamacher** [comment]
Bonjour,

Nous vous remercions pour votre feedback.

Le verbe lié à la création d'un poll a été modifié en conséquence (PUT => POST)

Cordialement.

**Comment by wasadigi** [comment]
Très bien! Vous avez vérifié toutes les ressources? Je ne me souviens pas (et j’avais parcouru la doc d’API assez rapidement), mais il me semble qu’il y avait plusieurs fois le cas?

Olivier Liechti

**Comment by julienamacher** [comment]
Nous avons effectivement relevé l'endpoint permettant de modifier le mot de passe comme étant sujet à discussion (POST sur /account/password - ne faudrait-il pas effectuer un PUT à la place?) et allons en discuter à la prochaine occasion.

A priori, il ne devrait pas y avoir d'autres ambiguités. La spécification reste encore à finaliser et à être revue par chaque personne du groupe. Des modifications ne sont pas exclues et sont même attendues.

Cordialement.
